name: PK
description: "PK social media"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4



flutter:
  uses-material-design: true

  assets:
    - assets/

  # اگر فونت خاصی داشتی اینجا اضافه کن
  # fonts:
  #   - family: IRANSans
  #     fonts:
  #       - asset: fonts/IRANSans.ttf



